---
title: "population data: retrieval and wrangling"
subtitle: "Census 2021: Census Subdivisions"
author: "Martin Monkman"
date: "2023-06-29"
output: html_document
---

```{r setup}
# packages
library(tidyverse)
library(readxl)
library(glue)


# create list of Vancouver Island CDs numbers
vi_cd_list <- c("17", "19", "21", "23", "24", "26", "27", "43", "45")

five_year_bins <- c(
  "0 to 4 years",
  "5 to 9 years",
  "10 to 14 years",
  "15 to 19 years",
  "20 to 24 years",
  "25 to 29 years",
  "30 to 34 years",
  "35 to 39 years",
  "40 to 44 years",
  "45 to 49 years",
  "50 to 54 years",
  "55 to 59 years",
  "60 to 64 years",
  "65 to 69 years",
  "70 to 74 years",
  "75 to 79 years",
  "80 to 84 years",
  "85 to 89 years",
  "90 to 94 years",
  "95 to 99 years",
  "100 years and over"  
)


# absolute value AND comma function
# from https://stackoverflow.com/questions/37949473/how-do-you-make-ggplot-labels-use-both-labels-abs-and-labels-comma
abs_comma <- function (x, ...) {
  format(abs(x), ..., big.mark = ",", scientific = FALSE, trim = TRUE)
}

```


read data

```{r}
df_pop_csd_vi_5yr <- read_rds(here::here("data_statcan", "df_pop_csd_vi_5yr.rds"))

```



### Vancouver Island total



```{r}

df_pop_csd_vi_5yr_total <- df_pop_csd_vi_5yr |> 
  group_by(age_grp) |> 
  summarise(
    total_age_grp = sum(pop_total, na.rm = TRUE),
    total_men = sum(pop_men, na.rm = TRUE),
    total_women = sum(pop_women, na.rm = TRUE)
    ) |> 
  ungroup()

df_pop_csd_vi_5yr_total <- df_pop_csd_vi_5yr_total |> 
  mutate(total_population = sum(total_age_grp)) |> 
    mutate(
    pct_men = total_men / total_population * 100,
    pct_women = total_women / total_population * 100
  )

df_pop_csd_vi_5yr_total

```


df_pop_csd_vi_5yr

```{r}
# prep for plot

df_pop_csd_vi_5yr_total <- df_pop_csd_vi_5yr |> 
  group_by(age_grp) |> 
  summarise(
    total_age_grp = sum(pop_total, na.rm = TRUE),
    total_men = sum(pop_men, na.rm = TRUE),
    total_women = sum(pop_women, na.rm = TRUE)
    ) |> 
  ungroup()


df_pop_csd_vi_5yr_total <- df_pop_csd_vi_5yr_total |> 
  mutate(total_population = sum(total_age_grp)) |> 
    mutate(
    pct_men = total_men / total_population * 100,
    pct_women = total_women / total_population * 100
  )

df_pop_csd_vi_5yr_total
df_pop_pyramid_csd <- df_pop_csd_vi_5yr |> 
  select(-contains("total"),
         -contains("pct_age_grp")) |> 
  # set value of men to negative
  mutate(
    pop_men = -pop_men,
    pct_men = -pct_men
  ) |> 
  pivot_longer(-c(geo_name:age_grp), names_to = "gender", values_to = "pop_2021") 

df_pop_pyramid_csd

df_pl_vi_pyramid <- 
  df_pop_csd_vi_5yr_total |> 
  select(age_grp, pct_men, pct_women) |> 
  mutate(pct_men = -pct_men) |> 
  pivot_longer(-age_grp, names_to = "gender", values_to = "pct_of_pop") 

df_pl_vi_pyramid_total <- 
  df_pop_csd_vi_5yr_total |> 
  select(age_grp, total_men, total_women) |> 
  mutate(total_men = -total_men) |> 
  pivot_longer(-age_grp, names_to = "gender", values_to = "pop_total") 

```



#### total pop

```{r}

community_total_population <- sum(abs(df_pl_vi_pyramid_total$pop_total))
community_total_population <- format(community_total_population, big.mark = ",", trim = TRUE)


# and plot
pl_pyramid_vi <-  
  ggplot(df_pl_vi_pyramid_total, aes(x = pop_total,
           y = age_grp,
           fill = gender
           )) + 
  geom_col() +
  theme_classic() +
  scale_fill_manual(
    values=c("#0C3343", "#EF5A27"),          # dark blue and action orange
    labels=c("men", "women")
    )  +
  xlab("population") +
  ylab(NULL)

#pl_pyramid_vi

# fix scale numbering

pop_range_breaks <- seq(-70000, 70000, by = 10000)

pl_pyramid_vi_total <- pl_pyramid_vi +
  scale_x_continuous(
    breaks  = pop_range_breaks,
    #                      limits = c(min(pop_range_breaks), max(pop_range_breaks)),
    limits = c(-70000, 70000),
#   labels = abs(pop_range_breaks)
#    labels = scales::comma
   labels = abs_comma  # custom function that combines absolute value AND commas
  )  +
# add vertical white "gridlines"
  geom_vline(xintercept = pop_range_breaks, col="white") +
  labs(title = "Vancouver Island",
       subtitle = glue::glue("total population = {community_total_population}"),

       caption = "Census 2021: Statistics Canada") +
  theme(legend.position = "bottom")

pl_pyramid_vi_total


ggsave(here::here("plot_output/pyramid_van_isl_2021_population.jpg"),
       width = 13.333,
       height = 7.5
  )


```




#### pct of pop

```{r}
  
# and plot
pl_pyramid_vi <-  
  ggplot(df_pl_vi_pyramid, aes(x = pct_of_pop,
           y = age_grp,
           fill = gender
           )) + 
  geom_col() +
  theme_classic() +
  scale_fill_manual(
    values=c("#0C3343", "#EF5A27"),          # dark blue and action orange
    labels=c("percent men", "percent women")
    )  +
  xlab("percent of population") +
  ylab(NULL)

#pl_pyramid_vi

# fix scale numbering

pop_range_breaks <- seq(-8, 8, by = 2)

pl_pyramid_vi +
   scale_x_continuous(breaks  = pop_range_breaks,
#                      limits = c(min(pop_range_breaks), max(pop_range_breaks)),
                      limits = c(-9, 9),
                       labels = abs(pop_range_breaks))  +
# add vertical white "gridlines"
#  geom_vline(xintercept = pop_range_breaks, col="white") +
  labs(title = "Vancouver Island",
       subtitle = glue::glue("total population = {community_total_population}"),

       caption = "Census 2021: Statistics Canada") +
  theme(legend.position = "bottom")


ggsave(here::here("plot_output/pyramid_van_isl_2021_pct.jpg"),
       width = 13.333,
       height = 7.5
  )


```

version 2 without such long (needed for Qualicum comparison) scale

```{r}

# fix scale numbering

pop_range_breaks <- seq(-5, 5, by = 1)

pl_pyramid_vi +
   scale_x_continuous(breaks  = pop_range_breaks,
#                      limits = c(min(pop_range_breaks), max(pop_range_breaks)),
                      limits = c(-5, 5),
                       labels = abs(pop_range_breaks))  +
# add vertical white "gridlines"
#  geom_vline(xintercept = pop_range_breaks, col="white") +
  labs(title = "Vancouver Island",
       subtitle = glue::glue("total population = {community_total_population}"),

       caption = "Census 2021: Statistics Canada") +
  theme(legend.position = "bottom")


ggsave(here::here("plot_output/pyramid_van_isl_2021_pct_shortscale.jpg"),
       width = 13.333,
       height = 7.5
  )

```



## pop pyramid function

```{r pop_pyramid_fun}

pop_pyramid_fun <- function(community_name, geo_csd_num){

# filter for community
df_pop_pyramid_community <- 
  df_pop_pyramid_csd |> 
  filter(case_when(
    community_name == community_name ~
    geo_name == community_name & geo_csd == geo_csd_num,
    TRUE ~ geo_name == community_name
  ))

# get total population of community
community_total_population <- df_pop_csd_vi_5yr |> 
  filter(case_when(
    community_name == community_name ~
    geo_name == community_name & geo_csd == geo_csd_num,
    TRUE ~ geo_name == community_name
  )) |> 
  summarise(total_pop = sum(pop_total)) |> 
  pull(total_pop)
community_total_population <- format(community_total_population, big.mark = ",", trim = TRUE)

### ---  

# now plot: total population
pl_pyramid_csd <- df_pop_pyramid_community |> 
  # filter for pop or pct
  filter(str_detect(gender, "pop")) |> 

ggplot(
  aes(x = pop_2021,
           y = age_grp,
           fill = gender)) + 
  geom_col()

# pl_pyramid_csd

# fix scale numbering

pop_range <- range(df_pop_pyramid_community$pop_2021)
#pop_range

pop_range_breaks <- pretty(pop_range)

pl_pyramid_csd +
   scale_x_continuous(breaks  = pop_range_breaks,
                       labels = abs(pop_range_breaks)) +
  theme_light() 


## overlay region

df_pyramid_csd <- 
 df_pop_pyramid_community |> 
  # filter for pop or pct
  filter(str_detect(gender, "pct"))  

# now plot
pl_pyramid_csd <- ggplot(
  df_pyramid_csd,
       aes(x = pop_2021,
           y = age_grp,
           fill = gender)) + 
  geom_col() +
  theme_classic() +
  scale_fill_manual(
    values=c("#0C3343", "#EF5A27"),          # dark blue and action orange
    labels=c("percent men", "percent women")
    )  +
  xlab("percent of population") +
  ylab(NULL)


# fix scale numbering
pop_range_breaks <- seq(-8, 8, by = 2)
pl_pyramid_csd <- pl_pyramid_csd +
   scale_x_continuous(breaks  = pop_range_breaks,
#                      limits = c(min(pop_range_breaks), max(pop_range_breaks)),
                      limits = c(-9, 9),
                       labels = abs(pop_range_breaks))  
#  geom_vline(xintercept = pop_range_breaks, col="white")


### ---

# overlay region as transparent grey

# overlay region
pl_pyramid_csd_region <- 
  pl_pyramid_csd +
  geom_col(
    aes(
      x = df_pl_vi_pyramid$pct_of_pop, 
      y = df_pl_vi_pyramid$age_grp,
      colour = gender 
      ),
    colour = "#E5E5E3",
    linewidth = 0.75,
    fill = "#E5E5E3", alpha = 0.33 
    )  
#  geom_vline(xintercept = pop_range_breaks, col="white")


# add title
pl_pyramid_csd_region <- pl_pyramid_csd_region +
  labs(
    title = community_name,
    subtitle = glue::glue("total population = {community_total_population}"),
    caption = "Census 2021: Statistics Canada"
  ) +
  theme(legend.position = "bottom")
  

return(pl_pyramid_csd_region)


}

```


### run function: individual

```{r}
# for some communities (eg Esquimalt) need to specify CSD number in filter 
# (due to duplication of name in CSD name) 

community_name <- "Qualicum Beach"
geo_cd_num <- "21"
geo_csd_num <- "023"

plot_temp <- pop_pyramid_fun(community_name, geo_csd_num)
plot_temp

ggsave(
  filename = 
    here::here(glue::glue("plot_output/pyramid_cd{geo_cd_num}_csd{geo_csd_num}_{community_name}_2021.jpg")), 
     plot_temp,
     width = 13.333,
     height = 7.5
  )

```


### run function: loop

```{r}
# for some communities (eg Esquimalt) need to specify CSD number in filter 
# (due to duplication of name in CSD name) 

community_list <- tribble(
  ~community_name, ~geo_csd_num,
  "Cumberland", "014",
  "Courtenay", "010",
  "Comox", "005",
  "Comox Valley A", "021",
  "Comox Valley B (Lazo North)", "022",
  "Comox Valley C (Puntledge - Black Creek)", "024"
)


vi_community_plots <- df_pop_pyramid_csd |> 
  # if specified in above list (comment next line out to run entire region)
  filter(geo_name %in% community_list$community_name) |> 
  distinct(geo_name, geo_cd, geo_csd)


vi_community_plots

```


```{r}
#plot_list <- vector(mode = "list", length = nrow(vi_community_plots))

plot_count <- nrow(vi_community_plots)

for (i in 1:nrow(vi_community_plots)) {
#  i <- 6
   community_name = vi_community_plots$geo_name[i]
   geo_cd_num <- vi_community_plots$geo_cd[i]
   geo_csd_num = vi_community_plots$geo_csd[i]
   plot_temp <- pop_pyramid_fun(community_name, geo_csd_num)
   plot_temp 
   
  ggsave(
    filename = 
    here::here(glue::glue("plot_output/pyramid_cd{geo_cd_num}_csd{geo_csd_num}_{community_name}_2021.jpg")), 
       plot_temp,
       width = 13.333,
       height = 7.5
    )

}

```


## Van Isl & Coastal Ec Dev region

### 5 year bins


```{r}
# from 01_data_retrieve_wrangle.Rmd
df_pop_er_canada <- read_rds(here::here("data_statcan", "df_pop_er_canada.rds"))


#unique(df_pop_er_canada$geo)
#unique(df_pop_er_canada$age_group)

```


filter 

```{r}
# filter for VIC and 5-year bins
df_pop_er_vic <- df_pop_er_canada |> 
  filter(geo == "Vancouver Island and Coast, British Columbia") |> 
  filter(age_group %in% five_year_bins_90) |> 
  filter(ref_date == 2021) |> 
#  filter(sex != "Both sexes") |> 
  select(
    ref_date,
#    date,
    geo,
    value,
    sex,
    "age_grp" = age_group
  )

```


```{r}
# prep for plot

df_pop_vic_5yr_total <- df_pop_er_vic |> 
  pivot_wider(id_cols = c(ref_date, geo, age_grp), names_from = sex, values_from = value) |> 
  rename(
    "pop_total" = `Both sexes`,
    "pop_men" = Males,
    "pop_women" = "Females"
  )
df_pop_vic_5yr_total
```



```{r}
df_pop_vic_5yr_total <- df_pop_vic_5yr_total |> 
#  mutate(total_population = sum(total_age_grp)) |> 
    mutate(
    pct_men = pop_men / sum(pop_total) * 100,
    pct_women = pop_women / sum(pop_total) * 100
  )
df_pop_vic_5yr_total
```


```{r}
df_pop_pyramid <- df_pop_vic_5yr_total |> 
  select(-contains("total"),
         -contains("pct_age_grp")) |> 
  # set value of men to negative
  mutate(
    pop_men = -pop_men,
    pct_men = -pct_men
  ) |> 
  pivot_longer(-c(ref_date:age_grp), names_to = "gender", values_to = "pop_2021") 

df_pop_pyramid
```


```{r}
df_pl_vic_pyramid <- 
  df_pop_vic_5yr_total |> 
  select(age_grp, pct_men, pct_women) |> 
  mutate(pct_men = -pct_men) |> 
  pivot_longer(-age_grp, names_to = "gender", values_to = "pct_of_pop") 

df_pl_vic_pyramid
```


median age

```{r}
# median age
df_pop_er_canada |> 
  filter(geo == "Vancouver Island and Coast, British Columbia") |> 
  filter(age_group == "Median age")

```

```{r}
  
# and plot
pl_pyramid_vi <-  
  ggplot(df_pl_vi_pyramid, aes(x = pct_of_pop,
           y = age_grp,
           fill = gender
           )) + 
  geom_col() +
  theme_classic() +
  scale_fill_manual(
    values=c("#0C3343", "#EF5A27"),          # dark blue and action orange
    labels=c("percent men", "percent women")
    )  +
  xlab("percent of population") +
  ylab(NULL)

#pl_pyramid_vi

# fix scale numbering

pop_range_breaks <- seq(-5, 5, by = 1)

pl_pyramid_vi +
   scale_x_continuous(breaks  = pop_range_breaks,
#                      limits = c(min(pop_range_breaks), max(pop_range_breaks)),
                      limits = c(-5, 5),
                       labels = abs(pop_range_breaks))  +
# add vertical white "gridlines"
#  geom_vline(xintercept = pop_range_breaks, col="white") +
  labs(title = "Vancouver Island and Coastal",
       subtitle = glue::glue("total population = {community_total_population}"),

       caption = "Census 2021: Statistics Canada") +
  theme(legend.position = "bottom")


ggsave(here::here("plot_output/pyramid_van_isl_2021_pct.jpg"),
       width = 13.333,
       height = 7.5
  )


```

## -30-